# Generated by Django 5.2 on 2025-06-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_blogpost_slug_blogcategory_blogpost_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogcategory",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
